-- Starter Deck
INSERT OR IGNORE INTO deck (id, name, level, description, total_cards, is_active)
VALUES (1, 'Starter', 'starter', 'Basic English vocabulary for beginners', 50, 1);

-- Starter vocabulary (50 words)
INSERT OR IGNORE INTO card (deck_id, front, back, example_sentence) VALUES
(1, 'hello', 'xin chào', 'Hello, how are you?'),
(1, 'goodbye', 'tạm biệt', 'Goodbye, see you tomorrow!'),
(1, 'thank you', 'cảm ơn', 'Thank you for your help.'),
(1, 'please', 'làm ơn', 'Please sit down.'),
(1, 'sorry', 'xin lỗi', 'I am sorry for being late.'),
(1, 'yes', 'vâng/có', 'Yes, I agree.'),
(1, 'no', 'không', 'No, thank you.'),
(1, 'water', 'nước', 'Can I have some water?'),
(1, 'food', 'thức ăn', 'The food is delicious.'),
(1, 'house', 'nhà', 'This is my house.'),
(1, 'book', 'sách', 'I am reading a book.'),
(1, 'friend', 'bạn', 'She is my best friend.'),
(1, 'family', 'gia đình', 'I love my family.'),
(1, 'school', 'trường học', 'I go to school every day.'),
(1, 'work', 'làm việc', 'I work from home.'),
(1, 'time', 'thời gian', 'What time is it?'),
(1, 'day', 'ngày', 'Have a nice day!'),
(1, 'night', 'đêm', 'Good night!'),
(1, 'morning', 'buổi sáng', 'Good morning!'),
(1, 'happy', 'vui', 'I am very happy today.'),
(1, 'sad', 'buồn', 'Why are you sad?'),
(1, 'big', 'lớn', 'That is a big house.'),
(1, 'small', 'nhỏ', 'The cat is small.'),
(1, 'good', 'tốt', 'This is a good idea.'),
(1, 'bad', 'xấu/tồi', 'That was a bad day.'),
(1, 'eat', 'ăn', 'Let us eat lunch together.'),
(1, 'drink', 'uống', 'I drink coffee every morning.'),
(1, 'sleep', 'ngủ', 'I need to sleep early tonight.'),
(1, 'run', 'chạy', 'I run in the park every morning.'),
(1, 'walk', 'đi bộ', 'Let us walk to the store.'),
(1, 'love', 'yêu', 'I love learning new things.'),
(1, 'cat', 'con mèo', 'The cat is sleeping.'),
(1, 'dog', 'con chó', 'The dog is friendly.'),
(1, 'sun', 'mặt trời', 'The sun is shining brightly.'),
(1, 'moon', 'mặt trăng', 'The moon is full tonight.'),
(1, 'tree', 'cây', 'There is a big tree in the garden.'),
(1, 'flower', 'hoa', 'The flowers are beautiful.'),
(1, 'music', 'âm nhạc', 'I listen to music every day.'),
(1, 'color', 'màu sắc', 'What is your favorite color?'),
(1, 'red', 'đỏ', 'The apple is red.'),
(1, 'blue', 'xanh dương', 'The sky is blue.'),
(1, 'green', 'xanh lá', 'The grass is green.'),
(1, 'white', 'trắng', 'Snow is white.'),
(1, 'black', 'đen', 'I have a black cat.'),
(1, 'hand', 'bàn tay', 'Wash your hands before eating.'),
(1, 'eye', 'mắt', 'She has beautiful eyes.'),
(1, 'heart', 'trái tim', 'Follow your heart.'),
(1, 'money', 'tiền', 'Money cannot buy happiness.'),
(1, 'phone', 'điện thoại', 'Where is my phone?'),
(1, 'computer', 'máy tính', 'I use a computer for work.');
