-- A1 Vocabulary Deck
INSERT OR IGNORE INTO deck (id, name, level, description, total_cards, is_active)
VALUES (2, 'A1 - Elementary', 'A1', 'Elementary English vocabulary', 50, 1);

-- A1 vocabulary (50 words)
INSERT OR IGNORE INTO card (deck_id, front, back, example_sentence) VALUES
(2, 'weather', 'thời tiết', 'How is the weather today?'),
(2, 'breakfast', 'bữa sáng', 'I eat breakfast at 7am.'),
(2, 'lunch', 'bữa trưa', 'Let us have lunch together.'),
(2, 'dinner', 'bữa tối', 'Dinner is ready!'),
(2, 'kitchen', 'nhà bếp', 'She is cooking in the kitchen.'),
(2, 'bedroom', 'phòng ngủ', 'My bedroom is upstairs.'),
(2, 'bathroom', 'phòng tắm', 'The bathroom is clean.'),
(2, 'window', 'cửa sổ', 'Please open the window.'),
(2, 'door', 'cửa', 'Close the door please.'),
(2, 'chair', 'ghế', 'Sit on the chair.'),
(2, 'table', 'bàn', 'Put it on the table.'),
(2, 'clothes', 'quần áo', 'I need new clothes.'),
(2, 'shoes', 'giày', 'These shoes are comfortable.'),
(2, 'shirt', 'áo sơ mi', 'He wears a white shirt.'),
(2, 'pants', 'quần', 'I bought new pants.'),
(2, 'doctor', 'bác sĩ', 'I need to see a doctor.'),
(2, 'teacher', 'giáo viên', 'My teacher is very kind.'),
(2, 'student', 'học sinh', 'She is a good student.'),
(2, 'market', 'chợ', 'Let us go to the market.'),
(2, 'hospital', 'bệnh viện', 'The hospital is nearby.'),
(2, 'bus', 'xe buýt', 'I take the bus to work.'),
(2, 'train', 'tàu hỏa', 'The train is fast.'),
(2, 'car', 'ô tô', 'He drives a red car.'),
(2, 'bicycle', 'xe đạp', 'I ride my bicycle every day.'),
(2, 'street', 'đường phố', 'The street is busy.'),
(2, 'park', 'công viên', 'Let us go to the park.'),
(2, 'restaurant', 'nhà hàng', 'This restaurant is popular.'),
(2, 'coffee', 'cà phê', 'I drink coffee every morning.'),
(2, 'tea', 'trà', 'Would you like some tea?'),
(2, 'milk', 'sữa', 'Children need to drink milk.'),
(2, 'bread', 'bánh mì', 'I eat bread for breakfast.'),
(2, 'rice', 'cơm', 'Vietnamese people eat rice every day.'),
(2, 'chicken', 'thịt gà', 'I like fried chicken.'),
(2, 'fish', 'cá', 'This fish is fresh.'),
(2, 'fruit', 'trái cây', 'Eat more fruit for health.'),
(2, 'vegetable', 'rau', 'Vegetables are good for you.'),
(2, 'hot', 'nóng', 'The weather is very hot today.'),
(2, 'cold', 'lạnh', 'It is cold outside.'),
(2, 'rain', 'mưa', 'It will rain tomorrow.'),
(2, 'beautiful', 'đẹp', 'This city is beautiful.'),
(2, 'new', 'mới', 'I have a new phone.'),
(2, 'old', 'cũ', 'This building is very old.'),
(2, 'fast', 'nhanh', 'The car is very fast.'),
(2, 'slow', 'chậm', 'The turtle is slow.'),
(2, 'buy', 'mua', 'I want to buy a book.'),
(2, 'sell', 'bán', 'They sell fresh fruit here.'),
(2, 'open', 'mở', 'Open your book to page 5.'),
(2, 'close', 'đóng', 'Please close the window.'),
(2, 'write', 'viết', 'Write your name here.'),
(2, 'read', 'đọc', 'I like to read before bed.');

-- Update deck card count
UPDATE deck SET total_cards = 50 WHERE id = 2;
